export const ADD_NEW_SECTION = 'ADD_NEW_SECTION';
export const ADD_NEW_SECTION_FAILED = 'ADD_NEW_SECTION_FAILED';
export const ADD_NEW_SECTION_SUCCESS = 'ADD_NEW_SECTION_SUCCESS';

export const GET_LIST_SECTION = 'GET_LIST_SECTION';
export const GET_LIST_SECTION_FAILED = 'GET_LIST_SECTION_FAILED';
export const GET_LIST_SECTION_SUCCESS = 'GET_LIST_SECTION_SUCCESS';

export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ADD_NEW_TASK_FAILED = 'ADD_NEW_TASK_FAILED';
export const ADD_NEW_TASK_SUCCESS = 'ADD_NEW_TASK_SUCCESS';

