export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ADD_NEW_TASK_FAILED = 'ADD_NEW_TASK_FAILED';
export const ADD_NEW_TASK_SUCCESS = 'ADD_NEW_TASK_SUCCESS';

export const GET_LIST_TASK = 'GET_LIST_TASK';
export const GET_LIST_TASK_FAILED = 'GET_LIST_TASK_FAILED';
export const GET_LIST_TASK_SUCCESS = 'GET_LIST_TASK_SUCCESS';

export const UPDATE_STATE_TASK = 'UPDATE_STATE_TASK';
export const UPDATE_STATE_TASK_FAILED = 'UPDATE_STATE_TASK_FAILED';
export const UPDATE_STATE_TASK_SUCCESS = 'UPDATE_STATE_TASK_SUCCESS';